[package]
name = "embedded_files_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"
clap = { version = "3.0.0-beta.5", features = ["yaml"] }
rust-embed="6.2.0"
